id: P005475
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9305
  title: ཇོ་ནང་ཏཱ་ར་ནཱ་ཐའི་རྣམ་ཐར་གྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    f779c1c21b8d4d43988e95eb3873b35c:
      image_group_id: I1KG9400
      title: ''
      volume_number: 1
      total_pages: 71
      base_file: v001.txt
